<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="BDN" name="latihan.testing.TestTimeout" tests="2" failures="0" timestamp="2020-05-02T11:30:34 ICT" time="5.105" errors="1">
  <testcase name="testThisShouldPass" time="4.008" classname="latihan.testing.TestTimeout"/>
  <testcase name="testThisShouldFail" time="1.097" classname="latihan.testing.TestTimeout">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method latihan.testing.TestTimeout.testThisShouldFail() didn&#039;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method latihan.testing.TestTimeout.testThisShouldFail() didn't finish within the time-out 1000
at latihan.testing.TestTimeout.testThisShouldFail(TestTimeout.java:13)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:51)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:41)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- testThisShouldFail -->
</testsuite> <!-- latihan.testing.TestTimeout -->
